<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_Address.FirstName</name>
   <tag></tag>
   <elementGuidId>98fb70b6-d915-4cc3-9188-27fdab798e15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_FirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Address_FirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24850b85-3941-4d2c-9aa4-07ef1630c266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>59e268a7-f1ac-4c77-918f-3c6f1687e233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>594cd54f-7fca-46ec-92ac-406830773281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>First name is required.</value>
      <webElementGuid>8eba5254-a536-440d-9886-77dc11c2f16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_FirstName</value>
      <webElementGuid>f6e2d30d-0396-4664-a011-5792d32bd825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.FirstName</value>
      <webElementGuid>0e529412-d8f4-402c-9f9f-cded5cd594c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba12807c-dd4a-4eda-a61d-b1e832358fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_FirstName&quot;)</value>
      <webElementGuid>1b553249-7c2f-46e2-8dd4-e598a3b4cc83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_FirstName']</value>
      <webElementGuid>098b0da8-3ef6-438c-bae0-0ba52255abf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>96045150-3fb4-453e-b4fe-ef67401969dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Address_FirstName' and @name = 'Address.FirstName' and @type = 'text']</value>
      <webElementGuid>e6fb6e40-4162-430b-ab5e-192cb34c9425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
