<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_Address.City</name>
   <tag></tag>
   <elementGuidId>2300274e-a614-414c-86ca-f8491b14b87f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_City</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Address_City']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bde6e4f1-ce98-4140-8491-8ca287ef1751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>cee3d004-8b81-48c8-b38e-c71029e4d8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74f97074-97d8-4d8d-9d7b-2a389d5fb062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>City is required</value>
      <webElementGuid>00c74cf6-e862-4dc3-8fc7-970593f9973b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_City</value>
      <webElementGuid>70d64bc6-86ce-4579-ab37-3395429daa1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.City</value>
      <webElementGuid>a4fb3245-3c21-4e1d-ae98-5ad52c8e9a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc8dc069-3466-41f3-9ff9-185dc40fb20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_City&quot;)</value>
      <webElementGuid>40263f92-4688-4bd4-aeab-f32f02d174a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_City']</value>
      <webElementGuid>55b64f97-e01f-4645-aade-a45a6abfd568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>b38000dd-23d8-4903-8df8-6e3522ef2670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Address_City' and @name = 'Address.City' and @type = 'text']</value>
      <webElementGuid>cb02f0f8-c6cd-4de4-967f-760ebc0a3df4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
