<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fax number_PickUpInStore</name>
   <tag></tag>
   <elementGuidId>b0026590-32bb-462b-8cc1-18729d9c22e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PickUpInStore</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PickUpInStore']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57a2313b-49df-49bb-ac6c-09e6a78d0ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PickUpInStore</value>
      <webElementGuid>8d35934b-5b36-458a-ae6b-95a50d851f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PickUpInStore</value>
      <webElementGuid>4d6b1654-cc42-4669-9a72-9f4f25f2c616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Shipping.togglePickUpInStore(this)</value>
      <webElementGuid>23af0dff-df13-4bb2-97f0-33ad904366d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d570f2c7-b9d4-4394-bc84-94a2693a6d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bfd85836-6555-4e0d-8ed4-b3990dcc125a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PickUpInStore&quot;)</value>
      <webElementGuid>1f2166a1-48de-41aa-b37b-48e4e7878833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PickUpInStore']</value>
      <webElementGuid>a05d65b2-f612-47b3-ad2b-e3ad590df798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-load']/div/div[2]/p/input</value>
      <webElementGuid>9fc10aae-cf83-4b09-8fe8-c0fc59f474d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>7d8f6890-689a-4344-ad8a-8af8dad207b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PickUpInStore' and @name = 'PickUpInStore' and @type = 'checkbox']</value>
      <webElementGuid>b9afe793-9bd5-4065-9a53-a922b50ce826</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
