<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card code_CardCode</name>
   <tag></tag>
   <elementGuidId>b2f7f1b3-cab5-45fe-874b-0aa6f637f66b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CardCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6073f794-afea-4a0f-8e60-a7792c9f606a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>17a2ed1d-b32f-41be-8f3a-2b7d5f64d578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardCode</value>
      <webElementGuid>ad10b5dd-96a7-4895-8120-8012333aaeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5899710c-deb0-45c8-b4ad-f38b031d0039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CardCode</value>
      <webElementGuid>f9088fa0-b6ca-4716-a66a-a42adab1da3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33bf4278-8033-4d9b-a1a6-c76402f1c0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardCode&quot;)</value>
      <webElementGuid>a3821190-74b2-4ce8-9632-90167b006e61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CardCode']</value>
      <webElementGuid>e451780b-75fe-438c-babe-0cd0993fb0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-info-load']/div/div/div/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>5131eb73-1354-4790-b606-b06e0b42dc88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>1c89903e-8d63-4e3f-93f2-a29d9f3b98cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CardCode' and @name = 'CardCode' and @type = 'text']</value>
      <webElementGuid>8eeaff5c-e8b4-4da5-b696-f622bca27478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
