<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_VisaMaster cardDiscoverAmex</name>
   <tag></tag>
   <elementGuidId>924b8938-845a-4ca8-9c06-09b7466762eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CreditCardType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CreditCardType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b4b7f4d8-9148-402e-87de-1453150c167c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdownlists</value>
      <webElementGuid>1469e3cb-9db6-4b12-8235-fd1e86d219b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CreditCardType</value>
      <webElementGuid>34aa98b6-5eb1-409c-b5c7-9a88fbc99f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CreditCardType</value>
      <webElementGuid>7aea2b2b-0f88-4ce8-9b75-942d5bf054d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visa
Master card
Discover
Amex
</value>
      <webElementGuid>25ec94d0-9436-499e-b893-5fedc999d599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreditCardType&quot;)</value>
      <webElementGuid>31fb70ef-ffff-45fb-ba02-f4111c6253a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CreditCardType']</value>
      <webElementGuid>9f1293d0-31e5-40ec-9769-59befb6008d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-info-load']/div/div/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>4183ee44-6bd2-4e26-addc-5b64ade8ce88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select credit card'])[1]/following::select[1]</value>
      <webElementGuid>1b8446cd-99fa-4ede-ac9a-93bcbde9302a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardholder name'])[1]/preceding::select[1]</value>
      <webElementGuid>fb4435e5-ac86-47ce-8cee-779ba5febe6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>48bbacc9-da9c-4533-b89b-1e2620dee5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CreditCardType' and @name = 'CreditCardType' and (text() = 'Visa
Master card
Discover
Amex
' or . = 'Visa
Master card
Discover
Amex
')]</value>
      <webElementGuid>ed7199f4-6938-4326-833c-8053324b8d92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
